name: ateliersou
favicon: null
layout_spectrum: 0.50043
typography_spectrum: 1
title: Atelier Sou
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b6afa7'
    - '#8e8878'
    - '#040404'
    - '#fbeace'
    - '#24332e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
